### PR TITLE
modified two.txt

### PR DESCRIPTION
**Pull request by sainathgaripally**
Hi Saikumar,

I have done the changes please merge it

### CODE REVIEW

**Review by Saikumarhardik — CHANGES_REQUESTED** [review]
Hi Sainath,

Please remove the line totally

**Review by sainathgaripally — COMMENTED** [review]
I have removed the line, pls approve

**Review by Saikumarhardik — APPROVED** [review]
This looks good sainath

**Comment by sainathgaripally** [comment]
Im closing the pull request

**Pull request closed without merging**
